---
namespace: sonarqube-h2

stack:
  defines: process-group
  runnable-list:
    - sonarqube-h2/sonarqube
    - sonarqube-h2/nginx
  variables:
    defines: variables
    nginx-listen-port:
      type: int
      value: 80
    nginx-image-tag:
      type: string
      value: latest
    sonarqube-image-tag:
      type: string
      value: lts-community
