namespace: sonarqube-postgresql

stack:
  defines: process-group
  runnable-list:
    - sonarqube-postgresql/database
    - sonarqube-postgresql/sonarqube
    - sonarqube-postgresql/nginx
  variables:
    defines: variables
    database-user:
      type: string
      value: "sonarqube"
    database-password:
      type: string
      value: "password"
    database-name:
      type: string
      value: "sonarqube"
    nginx-listen-port:
      type: int
      value: 80
    nginx-image-tag: 
       type: string
       value: "latest" 
    sonarqube-server-name:
      type: string
      value: sonarqube.example.com 
    sonarqube-image-tag:
      type: string
      value: lts-community